### PR TITLE
use ember-cli-node-assets instead of merge-trees

### PR DESCRIPTION
**Pull request by foxnewsnetwork**
Background
===
The ember-redux core library, the redux service currently lives in `ember-redux/app/services/redux.js` which is truly unfortunate as it gives no way for the end user to `import ReduxService from 'ember-redux/services/redux'` in the event they need to customize the redux-ember integration in some way.

As a platform concern, we ideally want to move the `ReduxService` out of `app` and into `addon` because this will not only provide easier customization user experience to the programmer, but also be a lot more conforming to existing ember-cli convention.

To do this, we need to make the following changes:

Changes
===
* install and use `ember-cli-node-assets`, `ember-cli-version-checker` and `broccoli-stew` instead of `broccoli-merge-trees` and `broccoli-funnel`
* elevate `redux-thunk` to `dependencies` from `devDependencies`
* re-write `index.js` to use `ember-cli-node-assets`
* remove unnecessary blueprint for installing redux-thunk

Advantages
===
* ember-redux will no longer by gimped by this shim, and therefore become able to elevate the redux service into the `addon` directory
* users of ember-fastboot will also be able to properly include redux-thunk as a part of server-side solution

Drawbacks
===
<del>* We must now enforce users be on ember-cli `>=2.10.0` as redux-thunk is distributed using anonymous AMD which isn't supported in ember-cli until `2.10.0` </del>
* We now require `ember-cli-version-checker` as an additional run-time  dependency. This isn't too big of a deal as I believe this library is used in ember-cli itself

References
===
* ember-cli anonymous AMD support - https://github.com/ember-cli/ember-cli/pull/5512
* ember-redux PR to move redux service into addon - TODO

Final Notes
===
If this PR is accepted, we'll need to bump major version to 2 as this is a breaking change

**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #none# - documentation fixes and/or test additions
- [ ] #patch# - backwards-compatible bug fix
- [x] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG

* install and use `ember-cli-node-assets` instead of `broccoli-merge-trees` and `broccoli-funnel`
* elevate `redux-thunk` to `dependencies` from `devDependencies`
* re-write `index.js` to use `ember-cli-node-assets`
* remove unnecessary blueprint for installing redux-thunk
* add a `lib/amd-shim` to shim AMDs for people stuck on earlier version of ember-cli

### CODE REVIEW

**Comment by toranb** [comment]
@foxnewsnetwork we simply can't require ember-cli v2.10 at this time :( sorry dude. We had a big pros/cons debate back in Nov/Dec 2016 and some key players are still on a much older version of ember-cli (who use this addon/ want to keep building on it).

**Comment by foxnewsnetwork** [comment]
All right, it's possible to still use ember-cli-node-assets without using the stuff in `dist` though (which would enable not requiring ember-cli 2.10.x); going to look into it. There may yet be hope for everyone

**Comment by toranb** [comment]
@foxnewsnetwork got another PR up to modernize the build/ ember-cli / etc 

Worth a look when you get a minute. 

About this PR - I'm still trying to understand the value add of the new dependencies / custom amd shim code / etc

If I'm critical here, the amount of code we are adding to wrap 14 lines of code from the real `redux-thunk` source isn't worth the maintenance burden.

https://github.com/gaearon/redux-thunk/blob/master/src/index.js

**Comment by foxnewsnetwork** [comment]
LOL I absolutely agree; but I was under the impression that we had to do this because other wise we weren't able to properly `import thunk from 'redux-thunk'` from the addon directory. If this isn't the case anymore, then great

**Comment by toranb** [comment]
@foxnewsnetwork thanks again - the AMD shim stuff you added here is something I was looking for last week (for another project) so thank you!

**Pull request closed without merging**
